<form class="form container" action="<?= $block->getUrl('getdecision/Index/getCustomerDecision'); ?>" method="post" autocomplete="off">
   <h1>WGRedmond FraudFighter Module tests</h1>
   
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>">
            <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
            </button>   
           
        </div>
    </div>
</form>
